### ISSUE TITLE
Bug: single-click interactions require double-click

### ISSUE THREAD

**Issue by ctbailey** [HackPlan/quark-shell-mac#42] opened 2015-05-29 00:03 UTC
Hi there,

Great project. Really appreciate the opportunity to use web standard technology to make native Mac apps. :)

To reproduce the bug:

1. Click the "Play" button in Xcode. Xcode builds Quark Shell and automatically gives it focus.
2. Click on a *different* app (e.g., Xcode, Chrome) to give that app focus.
3. Click the Quark Shell app icon in the status bar again. Now it takes a double-click to interact with buttons instead of the expected single click. For example, I don't see a notification appear on my screen unless I double click the "Notification" button.

This problem doesn't arise if you click the Quark Shell app icon immediately after clicking the play button. This makes me think the bug appears when you click the Quark Shell app icon while another app has focus.

If you have any trouble reproducing the bug, let me know. I'd be happy to make a screencast or something.

**Comment by xhacker** [comment] 2015-06-07 07:00
Sorry I can't reproduce the issue, can you elaborate more or make a screencast? Thanks!

**Comment by ctbailey** [comment] 2015-06-07 21:36
Sure. Here's the screencast:

https://youtu.be/5ugnxxCsb6Q

It includes annotations explaining the problem.

**Comment by ctbailey** [comment] 2015-06-07 21:49
Meant to include this earlier. System details:

![screen shot 2015-06-07 at 5 48 49 pm](https://cloud.githubusercontent.com/assets/5033974/8026258/8f14b0f2-0d3d-11e5-895e-45a5ccce4a2e.png)

**Comment by xhacker** [comment] 2015-06-07 22:18
@ctbailey: I get your point, but still can’t reproduce. I’m running 10.10.3 on exactly the same hardware. Have you installed any window/menubar management software?

**Comment by ctbailey** [comment] 2015-06-07 22:45
Just upgraded to 10.10.3 and the problem went away. 

I was getting this issue even when the project was exported from Xcode, though, so this would still affect users running earlier versions of OS X.

**Comment by ctbailey** [comment] 2015-06-07 22:46
There's a chance it was an issue in Xcode or something that was resolved by the OS update.

**Comment by xhacker** [comment] 2015-06-07 22:48
Thanks for the reply. Then I’d close this issue since it was an Apple issue and has already been resolved.

**Comment by ctbailey** [comment] 2015-06-07 22:52
I don't think this issue should be closed. We only know it's resolved **for users of 10.10.3**. There's no guarantee that apps exported from Xcode on 10.10.3 will work properly on 10.10.2. We need to test that.

**Comment by xhacker** [comment] 2015-06-07 22:58
Do you still have any 10.10.2 machines?

**Comment by xhacker** [comment] 2015-09-09 06:14
I don’t think we have enough bandwidth to support all the old minor versions. As 10.10.5 has already been released, I’m closing this.

**Closed by xhacker** 2015-09-09 06:14 UTC
